services:
  configurator-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: configurator-server
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    restart: unless-stopped
    ports:
      - 5000:5000
      - 5005:5005
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=configurator

  db:
    image: postgres:17
    container_name: configurator-db
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: configurator
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
